import { Toaster } from "@/components/ui/sonner";
import { GlobalProvider } from "@/context/global-context";
import { WebRTCProvider } from "@/contexts/web-rtc-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <WebRTCProvider>{children}</WebRTCProvider>
        </GlobalProvider>
      </body>
      <Toaster />
    </html>
  );
}
